export const PAGE_NAMES = {
    START: 'START',
    TRAINING: 'TRAINING',
    LEVEL_1_INTRO: 'LEVEL_1_INTRO',
    LEVEL_1_LOADING: 'LEVEL_1_LOADING',
    LEVEL_1_GAME: 'LEVEL_1_GAME',
    LEVEL_2_INTRO: 'LEVEL_2_INTRO',
    LEVEL_2_LOADING: 'LEVEL_2_LOADING',
    LEVEL_2_GAME: 'LEVEL_2_GAME',
    LEVEL_3_INTRO: 'LEVEL_3_INTRO',
    LEVEL_3_LOADING: 'LEVEL_3_LOADING',
    LEVEL_3_GAME: 'LEVEL_3_GAME',
    FINAL: 'FINAL',
};

export const NEXT_PAGES = {
    [PAGE_NAMES.START]: PAGE_NAMES.TRAINING,
    [PAGE_NAMES.TRAINING]: PAGE_NAMES.LEVEL_1_INTRO,
    [PAGE_NAMES.LEVEL_1_INTRO]: PAGE_NAMES.LEVEL_1_LOADING,
    [PAGE_NAMES.LEVEL_1_LOADING]: PAGE_NAMES.LEVEL_1_GAME,
    [PAGE_NAMES.LEVEL_1_GAME]: PAGE_NAMES.LEVEL_2_INTRO,
    [PAGE_NAMES.LEVEL_2_INTRO]: PAGE_NAMES.LEVEL_2_LOADING,
    [PAGE_NAMES.LEVEL_2_LOADING]: PAGE_NAMES.LEVEL_2_GAME,
    [PAGE_NAMES.LEVEL_2_GAME]: PAGE_NAMES.LEVEL_3_INTRO,
    [PAGE_NAMES.LEVEL_3_INTRO]: PAGE_NAMES.LEVEL_3_LOADING,
    [PAGE_NAMES.LEVEL_3_LOADING]: PAGE_NAMES.LEVEL_3_GAME,
    [PAGE_NAMES.LEVEL_3_GAME]: PAGE_NAMES.FINAL,
    [PAGE_NAMES.FINAL]: null,
};

export const RESET_PAGES_BY_LEVEL = {
    1: PAGE_NAMES.LEVEL_1_INTRO,
    2: PAGE_NAMES.LEVEL_2_INTRO,
    3: PAGE_NAMES.LEVEL_3_INTRO,
};
